### ISSUE TITLE
Remove incorrect code from CountryVitalRecords CS per GEC/ISO 3166-1

### ISSUE THREAD

**Issue by whichwit** [HL7/vr-common-library#78]
- `TC` is not valid for **United Arab Emirates**
https://github.com/HL7/vr-common-library/blob/0939eb2ab73e97367b105bd4169098b6d9308a88/input/fsh/codesystems/CodeSystemCountryVitalRecords.fsh#L252

- `PN` is not valid for **Panama** 
https://github.com/HL7/vr-common-library/blob/0939eb2ab73e97367b105bd4169098b6d9308a88/input/fsh/codesystems/CodeSystemCountryVitalRecords.fsh#L212

**Comment by saulakravitz** [comment]
Discussed at FHIR Leadership meeting.
These codes are needed.

**Comment by saulakravitz** [comment]
Discussed at FHIR Leadership meeting.
These codes are needed.
